In [8]:
from consultar_api_metar import obtener_metar, metar_a_dataframe, convertir_a_unix
from ventana_metar import main as descargar_ventana

In [9]:
fechainicio = convertir_a_unix("2026-05-09 15:00")
print(fechainicio)
fechafin = convertir_a_unix("2026-06-30 23:00")
print(fechafin)

1778338800
1782860400

In [10]:
datos = obtener_metar("SKBO", fechainicio, fechafin)
df = metar_a_dataframe(datos)

Consultando: SKBO desde 1778338800 hasta 1782860400
URL: https://simfac.fac.mil.co/api/1.0/metaresForOacisForTimes?beginDate=1778338800&endDate=1782860400&oacis=SKBO

In [11]:
df.head()

,OACI,Aeropuerto,Latitud,Longitud,Fecha,METAR,FECHA_HORA_REPORTE
0,SKBO,Bogotá / El Dorado,4.70306,-74.13833,09-05-2026 15:05:00,SKBO 091500Z 10009KT 050V150 CAVOK 19/04 Q1027...,2026-05-09 15:05:00
1,SKBO,Bogotá / El Dorado,4.70306,-74.13833,09-05-2026 16:05:00,SKBO 091600Z 11012KT 080V150 CAVOK 20/02 Q1026...,2026-05-09 16:05:00
2,SKBO,Bogotá / El Dorado,4.70306,-74.13833,09-05-2026 17:05:00,SKBO 091700Z 12011KT 090V160 9999 FEW060 20/07...,2026-05-09 17:05:00
3,SKBO,Bogotá / El Dorado,4.70306,-74.13833,09-05-2026 18:05:00,SKBO 091800Z 12009KT 050V170 9999 SCT060 21/07...,2026-05-09 18:05:00
4,SKBO,Bogotá / El Dorado,4.70306,-74.13833,09-05-2026 19:05:00,SKBO 091900Z 10008KT 060V160 9999 SCT050 21/08...,2026-05-09 19:05:00

In [1]:
from ventana_metar import descargar_ventana

In [3]:
df = descargar_ventana(oaci="SKBO", end="2026-05-09 15:00", hours=50)

Ventana: 50h desde 2026-05-07 13:00:00+00:00 hasta 2026-05-09 15:00:00+00:00
Consultando: SKBO desde 1778158800 hasta 1778338800
URL: https://simfac.fac.mil.co/api/1.0/metaresForOacisForTimes?beginDate=1778158800&endDate=1778338800&oacis=SKBO
Guardado: data/NewData/skbo_ventana.csv (60 registros)
Registros obtenidos: 60
Rango fechas: 2026-05-07 13:05:00 a 2026-05-09 15:05:00

In [5]:
df.tail()

,OACI,Aeropuerto,Latitud,Longitud,Fecha,METAR,FECHA_HORA_REPORTE
55,SKBO,Bogotá / El Dorado,4.70306,-74.13833,09-05-2026 13:05:00,SKBO 091300Z 05007KT 9999 VCFG NSC 13/10 Q1027...,2026-05-09 13:05:00
56,SKBO,Bogotá / El Dorado,4.70306,-74.13833,09-05-2026 13:05:00,SKBO 091321Z 05007KT CAVOK 15/10 Q1027 NOSIG =,2026-05-09 13:05:00
57,SKBO,Bogotá / El Dorado,4.70306,-74.13833,09-05-2026 14:05:00,SKBO 091400Z 05006KT 020V080 CAVOK 16/09 Q1027...,2026-05-09 14:05:00
58,SKBO,Bogotá / El Dorado,4.70306,-74.13833,09-05-2026 14:05:00,SKBO 091421Z 06009KT 030V090 CAVOK 18/08 Q1027...,2026-05-09 14:05:00
59,SKBO,Bogotá / El Dorado,4.70306,-74.13833,09-05-2026 15:05:00,SKBO 091500Z 10009KT 050V150 CAVOK 19/04 Q1027...,2026-05-09 15:05:00